# Numpy: Numeric computing library
Es una biblioteca para el lenguaje de programación Python, que agrega soporte para matrices y arreglos multidimensionales grandes, junto con una gran colección de funciones matemáticas de alto nivel para operar con estos arreglos.

## ¿Por qué Numpy es tan importante?
Por que el procesamiento de números con Python puro es muy lento especialmente cuando se trata de procesar una gran cantidad de datos, en cambio NumPy es una libreria de procesamiento de números muy eficiente ya que a bajo nivel trabaja con C, por ejemplo el número 5 con Python puro llega a pesar 20 bytes en cambio con NumPy pesa 3 bits

Por lo general no usaremos Numpy directamente, pero si lo usaremos a través de otras librerias como **Panda** o **Matplotlib**

## Arrays basicos con Numpy

In [2]:
import sys
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], b[1]

(np.int64(1), np.float64(0.5))

In [6]:
a[0:]

array([1, 2, 3, 4])

En el ejemplo de abajo 
- Indice 1: elemento se incluye
- Indice 3: no se incluye

In [7]:
a[1:3]

array([2, 3])

En el ejemplo de abajo
- Indice 1: Empieza de izquierda a derecha incluido resultado 2
- Indice -1: Empieza el último elemento pero sin incluirlo resultado 3

In [9]:
a[1:-1]

array([2, 3])

Como funciona el ejemplo de abajo:
- inicio: si es vacio empieza desde el inicio
- fin: si es vacio empieza hasta el final
- paso: si fuera igual a dos toma uno si y otro no

In [10]:
a[::2]

array([1, 3])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [13]:
b[[0, 2, -1]]

array([0., 1., 2.])

# Array Types

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

Que hace las funcion abajo:
- Crea un array a partir de una lista de enteros
- dtype=np.float64: convierte todos los elementos a números decimales de 64 bits

In [19]:
np.array([1,2,3,4], dtype=np.float64)

array([1., 2., 3., 4.])

In [20]:
c = np.array(['a', 'b', 'c'])

In [22]:
c.dtype

dtype('<U1')

A continuacion la explicacion de la funcion de abajo
- {'a': 1}: un diccionario
- sys: el módulo sys de Python (normalmente importado con import sys)
NumPy no puede convertir un diccionario y un módulo a un tipo númerico común, hace los posible: *Guarda referencias a objetos en Python*

In [23]:
d = np.array([{'a': 1}, sys])

In [24]:
d.dtype

dtype('O')

# Dimensiones y formas

In [25]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [27]:
A.shape #Esto nos devuelve las dimensiones de la matriz filas X columnas

(2, 3)

In [29]:
A.ndim # te dice cuantas dimensiones tien el array

2

In [31]:
A.size # devuelve la cantidad total de elementos del array, sin importar cuantas dimensiones tenga

6

In [32]:
B = np.array([
    [
        [12, 11, 18],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [33]:
B

array([[[12, 11, 18],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [34]:
B.shape

(2, 2, 3)

In [35]:
B.ndim

3

In [36]:
B.size

12

# Indexación y segmentación de matrices

In [38]:
# square matrix
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [39]:
A[1]

array([4, 5, 6])

In [40]:
A[1][0]

np.int64(4)

In [41]:
A[1,0]

np.int64(4)

In [42]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
A[:,:2] # Seleccionamos todas las filas y solo selecionamos 2 columnas

array([[1, 2],
       [4, 5],
       [7, 8]])

In [46]:
A[:2, :2] # Seleccionamos las primeras 2 filas y las 2 primeras columnas

array([[1, 2],
       [4, 5]])

In [49]:
A[1] = np.array([10,10,10]) # Cambiamos la fila 1 de la matriz por el array [10,10,10]

In [48]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

# Estadísticas resumidas

In [51]:
a = np.array([1,2,3,4])

In [53]:
a.sum() # Suma todos los elementos del array

np.int64(10)

In [54]:
a.mean() # Saca el promedio

np.float64(2.5)

**Calcular las deviacion estándar**

NumPy usa por defecto las deviación estándar poblacional

In [55]:
a.std()

np.float64(1.118033988749895)

In [60]:
a.var() # Calcula la virianza de los valores del array

np.float64(1.25)

In [57]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [58]:
A.sum()

np.int64(45)

In [59]:
A.mean()

np.float64(5.0)

In [61]:
A.std()

np.float64(2.581988897471611)

In [62]:
A.sum(axis=0) # suma por columnas

array([12, 15, 18])

In [64]:
A.sum(axis=1) # suma por filas

array([ 6, 15, 24])

In [65]:
A.mean(axis=0)

array([4., 5., 6.])

In [66]:
A.mean(axis=1)

array([2., 5., 8.])

In [67]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [68]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])