# Operaciones Vectorizadas y Broadcasting

In [4]:
import sys
import numpy as np

In [5]:
a = np.arange(4) # Crea un array de NumPy con números enteros desde 0 a 4, sin incluir el 4

In [4]:
a

array([0, 1, 2, 3])

In [7]:
a + 10 # Suma de un vectar con un escalar

array([10, 11, 12, 13])

In [9]:
a * 10 # Multiplicar un vector con un escalar

array([ 0, 10, 20, 30])

In [10]:
a += 100 # Con esta sentencia se esta modificando el valor del vector A

In [11]:
a

array([100, 101, 102, 103])

In [12]:
l = [0,1,2,3]

In [13]:
[i*10 for i in l]

[0, 10, 20, 30]

In [17]:
z = np.arange(5)

In [18]:
z + 20

array([20, 21, 22, 23, 24])

# Boolean Arrays

In [5]:
a = np.arange(4)

In [6]:
a

array([0, 1, 2, 3])

In [7]:
a[0], a[-1] # Primera forma: Muestra el primer y último elemento

(np.int64(0), np.int64(3))

In [8]:
a[[0, -1]] # Muesra el primer y últimos elemento segunda forma

array([0, 3])

**Diferencias principales**
~~~python
a[0] # Devuelve un solo valor
a[[0, -1]] # Devuelve varios valores
~~~

a[[0, -1]] Esto es super útil cuando se quiere seleccionar elementos especificos sin usar slicing

**Indexación booleana**

Estamos usando una mascara booleana para seleccionar elementos

**Importante**

La longitud de la mascara debe coincidir con la del array, sino *NumPy* lanza un error

In [9]:
a[[True, False, False, True]] # Muestra el primer y últimos elementos tercera forma

array([0, 3])

In [10]:
a * 10

array([ 0, 10, 20, 30])

**a >= 2** Compara cada elemento del array con 2, de forma vectorizada, como se evalua:

- 0 >= 2 -> False
- 1 >= 2 -> False
- 2 >= 2 -> True
- 3 >= 2 -> True

In [11]:
a >= 2

array([False, False,  True,  True])

In [12]:
a[a >= 2] # Filtra el array a y se queda solo con los valores mayores iguales a 2

array([2, 3])

In [14]:
a.mean() # Devuelve el promedio del vector

np.float64(1.5)

In [16]:
a[~(a > a.mean())] # Devuelve los elementos del vector que no son mayores al promedio

array([0, 1])

In [18]:
a[(a > a.mean())] # Devuelve los elementos del vector que son mayores al promedio

array([2, 3])

In [20]:
a[(a == 0) | (a == 1)] # Devuelve los elementos que son iguales a cero o uno

array([0, 1])

In [22]:
a[(a <= 2) & (a % 2 ==0)] # Devuevle los número pares menores o iguales a 2

array([0, 2])

**Arrays aleatorios**

- **np.random.randint(100)** Esta sentencia de abajo genera enteros aleatorios desde 0 a 100 (100 no incluido)
- **size=(3,3)** Define la forma del array: 3 filas por 3 columnas

**Nota** Los números cambian cada vez que se ejecuta la celda

In [23]:
A = np.random.randint(100, size=(3, 3))

In [24]:
A

array([[64, 43, 15],
       [38, 31, 71],
       [91, 17, 11]], dtype=int32)

In [26]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([64, 15, 31, 91, 11], dtype=int32)

In [27]:
A > 30

array([[ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

In [28]:
A[A > 30]

array([64, 43, 38, 31, 71, 91], dtype=int32)

In [30]:
c = np.arange(5)

In [31]:
c

array([0, 1, 2, 3, 4])

In [32]:
c <= 3

array([ True,  True,  True,  True, False])