# Introducción NumPy

Es una libreria open source que está ampliamentes usado en la ciencia e ingenieria. La libreria NumPy contiene estructuras de arrays multidimensionales, como el homogeneo *N-dimensional* ndarray.



## ¿Qué es NumPy?

Es una libreria que provee objetos multidimensionales como *Arrays* y *Matrices* y una variedad de rutinas para operaciones rápidas en matrices, incluidas matemáticas, lógicas, manipulación de formas, clasificación, selección, E/S, transformadas discretas de Fourier, álgebra lineal básica, operaciones estadísticas básicas, simulación aleatoria y mucho más.

En su nucleo el paquete de NumPy es un objeto ndarray. Este encapsual arrays *n-dimensionales* y tipos de datos homogeneos

**¿Por que NumPy es mas rápido?**

Una de las razones es por que utiliza tipos fijo (fixed types). Lo que signfica que, imaginemos que tenemos una matriz 3x4 y todos sus valores son enteros. Y nosotros vamos a analizar cómo difieren esos valores enteros entre NumPy y las listas.

Por ejemplo el 5 en binario se veria como: 00000101 y sus 8 bits lo que lo convierte en un **byte**. Y cuando usamos NumPy estos 8 bits por defecto se convertiran en un entero tipo **int32** que a su vez serian 8 bytes y esto representa.

Otra razón por la que NumPy es mas rápido que las listas, es que usa memoria continua, en cambio las Listas se almacenan en forma dispersa en la memoria 

In [1]:
import numpy as np
import sys

In [20]:
# Incializamos un array
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [21]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [22]:
# Get dimension
print(a.ndim) # 1 dimensión para el array
print(b.ndim) # 2 dimensiones para la matriz

1
2


In [23]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [24]:
# Get Type
print(a.dtype)
print(b.dtype)

int64
float64


In [31]:
# Si queremos especificar el tipo de valores

c = np.array([1, 2, 3], dtype='int32')
print(c.dtype)

int32


In [32]:
c.itemsize

4

In [36]:
# Get total size (numero de items)
b.size

6