# Inicializando diferentes Arrays

In [2]:
import numpy as np
import sys

In [6]:
np.zeros(5) #  Arrays de una dimensión

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((2, 3)) # Arrays de dos dimensiones

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((2, 3, 3)) # Arrays de tres dimensiones

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
np.zeros((2, 3, 3, 2)) # Arrays de cuatro dimensiones

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [13]:
np.ones((4, 2, 2), dtype='int32') # Matriz de 3 dimensiones con valores 1

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [15]:
# Creando una matriz de cualquier otro número
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [17]:
# Números decimales randomicos
np.random.rand(4, 2)

array([[0.68279023, 0.11682409],
       [0.45063669, 0.40133031],
       [0.96587125, 0.75207143],
       [0.24215945, 0.46362442]])

In [43]:
# Números enteros randomicos del 0 al 20
np.random.randint(20, size=(3, 3))

array([[ 6,  0,  7],
       [ 7, 13,  4],
       [15,  1, 17]], dtype=int32)

In [58]:
# Números enteros randomicos entre 4 y 10
np.random.randint(4, 10, size=(3, 3))

array([[7, 4, 4],
       [7, 8, 9],
       [5, 5, 7]], dtype=int32)

In [61]:
# Matriz identidad
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
# Repetir un array
arr = np.array([1, 2, 3, 4])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3 4 4 4]


In [66]:
# Repetir un array
arr = np.array([[1, 2, 3, 4]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [5]:
output = np.ones((5, 5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [8]:
# array[filas, columnas]
output[1: -1, 1: -1] = z

In [9]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Ser cuidadoso cuando se copian arrays

In [4]:
a = np.array([1, 2, 3])
b = a
b

array([1, 2, 3])

In [6]:
b[0] = 100
b

array([100,   2,   3])

In [8]:
a # Como se ve la anterior modificación no solo cambio el array B sino que tambien modifico el array A

array([100,   2,   3])

In [10]:
# Para solucionar este problema podemos usar la función copy()

a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]
