# Matemáticas

In [2]:
import numpy as np
import sys

In [5]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [6]:
a+2

array([3, 4, 5, 6])

In [7]:
a-2

array([-1,  0,  1,  2])

In [8]:
a * 2

array([2, 4, 6, 8])

In [9]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [11]:
# Multiplicación de un esacalar por un vector
x = np.array([2, -1, 4])
3 * x

array([ 6, -3, 12])

In [14]:
# Suma de vectores
b = np.array([1, 0, 1, 0])
print(a)
print(b)
print(a+b)

[1 2 3 4]
[1 0 1 0]
[2 2 4 4]


In [16]:
# Vector elevado a 2
a ** 2

array([ 1,  4,  9, 16])

In [17]:
# Sacando el seno de a
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Algebra Lineal

Con algebra lineal no es como, no lo estamos haciendo elemento por elemento. Entonces en este caso 

### Producto vectorial y producto matricial

**Ejemplo 1** Producto de un vector demanda y un vector de precio. Suponga que un fabricante producto cuatro articulos. La demanda de los articulos viene dada por el vector demanda d = (30, 20, 40, 10). El precio unitario que el fabricante recibe por los articulos esta dado por el 

vector de precios p = 20
                      15
                      18
                      40

Si se satisface la demanda, ¿que ingresos tendra el fabricante?

In [29]:
d = np.array([30, 20, 40, 10]) # Matriz 1 x 4
p = np.array([[20, 15, 18, 40]]) # Matriz 4 x 1
print(d)
print(p)
print(d.shape)
print(p.shape)

[30 20 40 10]
[[20 15 18 40]]
(4,)
(1, 4)


In [23]:
ganancia = d * p

In [25]:
ganancia.sum()

np.int64(2020)

In [27]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [31]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [33]:
# Encontrar la determinante
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

## Estadística

In [44]:
stats = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
stats

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
print(np.min(stats))
print(np.min(stats, axis = 0))

1
[1 2 3]


In [37]:
np.max(stats)

np.int64(6)