# Reorganizando arrays

In [1]:
import numpy as np
import sys

In [4]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8, 1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [9]:
after = before.reshape((4, 2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
after = before.reshape((2, 2, 2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Vectores de apilamiento vertical

In [12]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

print(np.vstack([v1, v2]))

print(np.vstack([v1, v2, v2, v2]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


### Vectores de apilamiento horizontal

In [16]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
print(h1)
print(h2)
np.hstack((h1, h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])