# Carga de datos e Inexación avanzada

In [2]:
import numpy as np
import sys

In [9]:
filedata = np.genfromtxt("data.txt", delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  45,  687,    1,    6,  874,  845, 1565,   82,  215,    2,   16,
         651],
       [  45,  545,    2,    5,  456,  987, 1598,   45,  154,    8,   45,
         952],
       [  98,  512,    6,    7,  159,  987, 1577,   54,  321,    5,   98,
         621]], dtype=int32)

### Indexación de datos avanzada

#### Enmascarmiento booleano e indexación avanzada

In [12]:
filedata > 50

array([[False,  True, False, False,  True,  True,  True,  True,  True,
        False, False,  True],
       [False,  True, False, False,  True,  True,  True, False,  True,
        False, False,  True],
       [ True,  True, False, False,  True,  True,  True,  True,  True,
        False,  True,  True]])

In [13]:
filedata[filedata > 50]

array([ 687,  874,  845, 1565,   82,  215,  651,  545,  456,  987, 1598,
        154,  952,   98,  512,  159,  987, 1577,   54,  321,   98,  621],
      dtype=int32)

#### Puedes indexar con una lista en Numpy

In [14]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [22]:
np.any(filedata > 50, axis = 0)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
       False,  True,  True])

In [17]:
filedata

array([[  45,  687,    1,    6,  874,  845, 1565,   82,  215,    2,   16,
         651],
       [  45,  545,    2,    5,  456,  987, 1598,   45,  154,    8,   45,
         952],
       [  98,  512,    6,    7,  159,  987, 1577,   54,  321,    5,   98,
         621]], dtype=int32)

In [23]:
np.all(filedata > 50, axis = 0)

array([False,  True, False, False,  True,  True,  True, False,  True,
       False, False,  True])

In [24]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False, False, False,  True, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False, False, False, False, False, False,  True, False,
        False,  True, False]])